<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirm_password</name>
   <tag></tag>
   <elementGuidId>75a66294-aa9c-4186-8299-7bbadaec9606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg_confirm_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reg_confirm_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f004928d-1423-46fc-a9f1-d02e5de596cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7dcc1099-1f19-42ee-80fe-d150bdf8e04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text woocommerce-Input woocommerce-Input--text</value>
      <webElementGuid>2492370d-5f63-4589-820e-52f0d59ada6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>41485aa5-4b7b-4694-8b1e-8d8fabb585ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg_confirm_password</value>
      <webElementGuid>815c2ca8-247a-414f-b55c-0bf37b6ee032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_confirm_password&quot;)</value>
      <webElementGuid>e435e96b-fae8-4a20-9a89-523ba7a5ea40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg_confirm_password']</value>
      <webElementGuid>e53e1aea-5335-4155-b9eb-21fc74102044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='reg_confirm_password_field']/span/span/input</value>
      <webElementGuid>40757ba1-8ef3-40fc-81e5-d2478ce96dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>f7897120-3aff-431e-8659-27d2e6e41d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @id = 'reg_confirm_password']</value>
      <webElementGuid>e1496fb9-6d8f-4447-ad4c-6f561387885e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
