<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_dahsboard_icon-user</name>
   <tag></tag>
   <elementGuidId>26082507-509c-444e-b64b-a1785c9b6bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='masthead']/div/div[4]/ul/li[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4bf0839e-863f-4e50-9bd1-15113ac59dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-user</value>
      <webElementGuid>551a6ff6-1870-482b-899a-166691111a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masthead&quot;)/div[@class=&quot;header-inner flex-row container logo-left medium-logo-center&quot;]/div[@class=&quot;flex-col hide-for-medium flex-right&quot;]/ul[@class=&quot;header-nav header-nav-main nav nav-right  nav-line-bottom nav-uppercase&quot;]/li[@class=&quot;account-item has-icon has-dropdown&quot;]/a[@class=&quot;account-link account-login
  is-small&quot;]/i[@class=&quot;icon-user&quot;]</value>
      <webElementGuid>9df7e537-8383-4d0c-8754-0d76644a2ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masthead']/div/div[4]/ul/li[3]/a/i</value>
      <webElementGuid>c2debc3b-0ec9-4794-a5f3-f2ddd064911c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[3]/a/i</value>
      <webElementGuid>447e1e28-f2ba-4a7f-bc8a-436907b0049d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
