<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneCulinaryTraveling  _80d3f1</name>
   <tag></tag>
   <elementGuidId>9a267aa8-0e50-4f7d-ab33-a589f9946d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5ea976d054e4e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5ea976d054e4e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9dc12c8a-78ec-430d-bf69-ce6639f32074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5ea976d054e4e</value>
      <webElementGuid>8f8cd047-ee80-4015-8eeb-781674ca1320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>1af699fb-66bf-4e44-8782-b9b7aa9f8387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5ea976d054e4e]</value>
      <webElementGuid>2195fa0e-76b7-4e86-8a16-56f680e96b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54a176b0-dad0-4907-8378-4b3be32f889b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e8f4c3f-7f79-4c9e-bf66-3f60cc60af72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50b62926-ae27-4c5a-802a-a5bd4fc4e646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>e38df876-8c96-4d60-a559-35f12fe68b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>717858bc-f22f-460a-a83c-3d8d345603c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles</value>
      <webElementGuid>d46a18e0-0b22-4efd-8d11-8214bf7fac33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5ea976d054e4e&quot;)</value>
      <webElementGuid>90a8b3f7-5aab-45c9-ae14-5222f287406e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5ea976d054e4e']</value>
      <webElementGuid>265cbb13-1b83-4f2d-8bc5-1ea9dd995fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>7402af7b-7c6a-4597-b0eb-b88ee55735eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>89cc6ac6-f372-49dc-8fb8-2e3e7674364c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>b1015347-7d66-467c-8319-cecad22f66ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>e11d4847-6bc2-4274-a167-8f80d2a8b0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5ea976d054e4e' and @name = 'acf[field_5ea976d054e4e]' and (text() = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles' or . = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles')]</value>
      <webElementGuid>e11c067a-a658-40d8-84b0-03bb01516d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
