<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OnePlaystationXBoxNintendoPC</name>
   <tag></tag>
   <elementGuidId>43f6eede-30b0-4660-8241-6e5514376919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e75905014c81']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e75905014c81</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2cf96a51-53ab-4f2d-9a7c-030cbc93365d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e75905014c81</value>
      <webElementGuid>25d9725a-a9e3-464a-85bc-972e101601ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>9c4c2448-cac2-474f-bd63-80e2372b8456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e75905014c81]</value>
      <webElementGuid>4aa10c00-0ddf-43b8-b3f0-62f39d55a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e16661de-1408-433e-bf8d-64d3258cd7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09262e7f-0469-4d1a-aff6-406163791950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9acc1cb-ed3f-4430-a3f3-e084c4699cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>e1797687-51fe-4b25-927c-bffe3de9e0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>737ccad2-59a8-4e82-a91d-e0cb560abc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OnePlaystationXBoxNintendoPC</value>
      <webElementGuid>832fd9af-c59b-407a-b77b-4f1db3629fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e75905014c81&quot;)</value>
      <webElementGuid>5c9990a5-cb42-42a5-8fff-31778c27b1ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e75905014c81']</value>
      <webElementGuid>25e44bc2-1f45-4100-8949-ec758dfd2bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[2]/div[2]/select</value>
      <webElementGuid>5419a89d-f2a7-4370-b957-6eed7113de2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>dd8e3d56-9bc2-4538-b1eb-a37c06e1060c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>c3de8a79-0ef8-4a45-9265-e22888d4b616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>709f4ff7-d7d2-4a2b-865a-925dc04f1be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e75905014c81' and @name = 'acf[field_5e75905014c81]' and (text() = 'Please Select OnePlaystationXBoxNintendoPC' or . = 'Please Select OnePlaystationXBoxNintendoPC')]</value>
      <webElementGuid>dc3f71d7-23b3-4899-a02b-218bd2d46169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
