<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneCulinaryTraveling  _80d3f1</name>
   <tag></tag>
   <elementGuidId>a11f707f-e23b-4a91-b725-b860ee2e2750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5ea976d054e4e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5ea976d054e4e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e3464289-ffc1-4cdb-98b6-a18296ea9ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5ea976d054e4e</value>
      <webElementGuid>98360883-62ee-4571-a1ee-d419263daf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>06e4e30c-0ba6-41c5-b506-dfe7685c778b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5ea976d054e4e]</value>
      <webElementGuid>88e9e836-676c-48ac-9ca9-c689a14e72ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9aa215e-18d7-49cb-ace2-3da11518dbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d9146412-14c7-464e-9afe-42319b48b382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>341e0b2c-ea65-493c-8eee-da11a38fb281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>d89032dc-c0d4-46ae-8124-60bf61147b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1abd3e3e-0551-4ff1-85da-ebd3f83f8fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles</value>
      <webElementGuid>92099e14-dde9-439b-bf5b-317bec24c80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5ea976d054e4e&quot;)</value>
      <webElementGuid>2b3290f2-a4cf-455e-aaca-6aef6201bfb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5ea976d054e4e']</value>
      <webElementGuid>74ed18b7-f675-4964-b690-f7de5c92cf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>6faef0ef-d0c0-4d86-acfb-810ef2fa8b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>d403fe0c-7d04-4e07-be62-e93c763cae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>fd961099-50a1-47aa-b16d-d4d8c27385ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>ce3dcf4a-cb91-4897-952f-4dc6910a554a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5ea976d054e4e' and @name = 'acf[field_5ea976d054e4e]' and (text() = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles' or . = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles')]</value>
      <webElementGuid>dde99cb9-a838-45b8-a129-f0ac015fbf02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
