<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__h9dmugl2kicg1670608448954</name>
   <tag></tag>
   <elementGuidId>33546bc1-831d-42ef-96ca-875a084fc5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='h9dmugl2kicg1670608448954']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#h9dmugl2kicg1670608448954</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a99e5da4-bc18-4d07-b1bc-5f763cadf952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>65e1b1d5-5730-4acc-bbd2-fa427ad661e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>176e7f5f-7171-45ed-87e7-ba2f56f17f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>eef577fa-ab89-4163-9383-2ed772acf9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>360px</value>
      <webElementGuid>03e6d40a-beaf-4e63-b2e2-4ca500de9bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>509px</value>
      <webElementGuid>c726e193-8f90-4a21-af62-80180b8311a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h9dmugl2kicg1670608448954</value>
      <webElementGuid>4eb4d2db-b648-4abb-9a1e-210f4afade13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>chat widget</value>
      <webElementGuid>aa6aed96-1904-4dd0-b405-100b691e3f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h9dmugl2kicg1670608448954&quot;)</value>
      <webElementGuid>2e33c537-dcbc-410c-a694-16e247c772e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='h9dmugl2kicg1670608448954']</value>
      <webElementGuid>fae78f32-818b-43eb-bf0f-5445daaea9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hasjid2spr1g1670608448761']/iframe[3]</value>
      <webElementGuid>52fb4638-dd2c-4b1f-8163-a0dfd0c0cb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>ac9d4bea-e29a-46ab-8231-ec7540df53c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @id = 'h9dmugl2kicg1670608448954' and @title = 'chat widget']</value>
      <webElementGuid>c35f4a97-9f24-4438-a555-023279f21781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
