<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneActionRacingSimulat_02dff3</name>
   <tag></tag>
   <elementGuidId>c1a2656c-f7b7-4631-ba43-42fb8a611338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e758bca4e8cc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6eb1b5b-561a-4750-896d-fae012dd4188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e758bca4e8cc</value>
      <webElementGuid>06287100-e8b0-4b6d-bc2f-01c3be47f5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>92f5451e-f59c-4f41-ada2-c5be7c4c48eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e758bca4e8cc]</value>
      <webElementGuid>3b7b9af7-1d57-4be2-ad08-fd47471e809e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f87171f-b5b6-4b1f-a6e7-efa6350d33f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4fa6873-c91c-49ed-a551-a140fe3285c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>44bb824e-8ce3-4601-9822-647cf3408691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>1a31a99e-f5c8-4ca0-8465-3bfc37fc94fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b350f531-f269-49ac-b0ac-cbf54549af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic</value>
      <webElementGuid>ccb84469-e20b-459e-9178-78de716efead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e758bca4e8cc&quot;)</value>
      <webElementGuid>8ac59700-a9bf-4679-be52-c6a216f2db6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      <webElementGuid>56ee157f-4d40-4e90-ae14-52fddfbf0489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div/div[2]/select</value>
      <webElementGuid>562ea4db-b460-4aa0-8948-8b54e1fa9afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>7014303b-77b1-4ff0-8db7-21bef324f7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>7d45713f-3f15-4d55-9e67-a857167eb15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4c24b313-d6bd-490d-ae54-dde442d165d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e758bca4e8cc' and @name = 'acf[field_5e758bca4e8cc]' and (text() = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic' or . = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic')]</value>
      <webElementGuid>7cacde83-be22-4b30-afa8-b56a37a81328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
