<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirm_password</name>
   <tag></tag>
   <elementGuidId>949925a1-c371-41b1-9e5a-2125c85872d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg_confirm_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reg_confirm_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04cf6485-aff0-43ba-b162-84852bfc8258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4e413a0d-a2d5-4aa0-8389-6e9151ed829d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text woocommerce-Input woocommerce-Input--text</value>
      <webElementGuid>24cdc38e-7e16-4ad3-8a44-fda27a9f9e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>4ee70cd7-62b8-4fd7-af11-a0267b122577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg_confirm_password</value>
      <webElementGuid>6eca7269-4d56-48a3-b912-e80a995b375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_confirm_password&quot;)</value>
      <webElementGuid>c59f8bde-d759-4fd1-8eb9-d7c617a456e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg_confirm_password']</value>
      <webElementGuid>9ab77fb1-e66f-42b0-a399-ce95b6aabf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='reg_confirm_password_field']/span/span/input</value>
      <webElementGuid>58ccc2e9-f338-48ba-8cfc-44624bfa7d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>c829c7b7-7eb1-469e-b431-0bfb036d0688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @id = 'reg_confirm_password']</value>
      <webElementGuid>70c94d05-cc87-4098-87ee-062cc40d7e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
