<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirm_password</name>
   <tag></tag>
   <elementGuidId>ba1cf9f0-e0fd-4a94-bda5-1795f1bf9c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg_confirm_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reg_confirm_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72042f3c-1861-42e3-9a40-b1bdf5b40ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>156c0caf-3491-430b-98cb-4f4aa0b43d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text woocommerce-Input woocommerce-Input--text</value>
      <webElementGuid>cc027b55-204c-4ad6-8bca-751fbd8558e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>7e867273-05d8-40b1-9cc8-0952b201f50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg_confirm_password</value>
      <webElementGuid>0e512057-959d-47e6-8d0f-2113678632a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_confirm_password&quot;)</value>
      <webElementGuid>a0f5997d-b300-4ceb-bc6f-c91aaecd5170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg_confirm_password']</value>
      <webElementGuid>0d7105fe-e691-4b04-95a6-e169dbec13b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='reg_confirm_password_field']/span/span/input</value>
      <webElementGuid>542bd6d7-2806-40f6-96c6-64cce0b9b729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>87b50eaa-e4c7-4464-80a0-f08db549e2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @id = 'reg_confirm_password']</value>
      <webElementGuid>844e406c-e251-47c3-8ec5-3ee5ec9f64b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
