<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneActionRacingSimulat_02dff3</name>
   <tag></tag>
   <elementGuidId>5e196e8b-3640-4ec5-bdbb-5ba1bd411076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e758bca4e8cc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3bfc01e-3e5d-466b-af66-56e7709534ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e758bca4e8cc</value>
      <webElementGuid>d78db0ac-2ec1-448d-b0d7-6c5394d51830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>59d2879c-b41d-4837-a07b-3ea30429a101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e758bca4e8cc]</value>
      <webElementGuid>b97752eb-0674-4983-ba0a-0fb628894178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4abaa72d-42d4-424b-b92a-41cdb8a65ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b904e87-15e8-4e61-a0a0-64413985413a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ddd00ad9-20eb-4b4c-9e9d-cda03190aba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>8860af13-64bf-4018-a1d5-f941f3a14692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dfd39041-3a5b-427d-81b5-df1552a6bab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic</value>
      <webElementGuid>67138d36-e31f-454f-a6d1-1106c56621d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e758bca4e8cc&quot;)</value>
      <webElementGuid>25a3b8c1-9824-438b-958f-0acd1532285f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      <webElementGuid>7bb935bf-c3d3-4b1a-943c-2d912fd87556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div/div[2]/select</value>
      <webElementGuid>51f65c59-45bf-4fda-a671-3b90561cae2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>b89e25c8-41d8-4195-853d-8785e8e95c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>3534f403-25c5-41eb-be91-d1fb462b37cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>16ea73fe-f80c-478f-8e93-0042e9354ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e758bca4e8cc' and @name = 'acf[field_5e758bca4e8cc]' and (text() = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic' or . = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic')]</value>
      <webElementGuid>0f7fc4bc-25a3-4d9c-a8f2-40a1dbf62ef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
