<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneCulinaryTraveling  _80d3f1</name>
   <tag></tag>
   <elementGuidId>9d7ca176-0f80-4ae6-90c7-fa2fdae14f8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5ea976d054e4e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5ea976d054e4e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0f86f760-815e-4a6d-91c2-6080e1d20388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5ea976d054e4e</value>
      <webElementGuid>567945d8-70be-4937-8b02-2c4fbba99079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>f8a91fdd-5662-40ce-ad25-6fcdac40f355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5ea976d054e4e]</value>
      <webElementGuid>635419f2-0490-4895-8ee0-168cebbf37d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>26930789-2c6a-40ea-8aa0-44b4be3bb5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>941a6989-7618-473f-b5b5-18c14a1fa94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0e9b57b-8c85-45ee-bba5-ba99a839eed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>07b8cfc5-a7f7-40d4-beb2-f541fc849fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c53c2600-e64e-4962-8864-80d1b5496d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles</value>
      <webElementGuid>77d1d67b-412f-4ca1-ad15-0ad2ec88b0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5ea976d054e4e&quot;)</value>
      <webElementGuid>0d333d35-1b98-405d-a7af-a67edb44c5af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5ea976d054e4e']</value>
      <webElementGuid>3c964888-14d8-4fe5-888d-f43053ff76c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>ebb17d37-cd8c-4b4d-9fd1-5de9a9297b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>a4a83570-5ca6-463c-8017-1a2b2e98334d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>47eec5c1-7b20-4a9d-be16-60f5c6010aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>400614e4-352d-44b3-9fd9-8f50e1e09b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5ea976d054e4e' and @name = 'acf[field_5ea976d054e4e]' and (text() = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles' or . = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles')]</value>
      <webElementGuid>265359df-d25f-4ec9-9339-e40f26f3c5ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
