<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneCulinaryTraveling  _80d3f1</name>
   <tag></tag>
   <elementGuidId>bfa9c68e-c8c9-42c1-955f-cac069c15cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5ea976d054e4e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5ea976d054e4e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>768c2683-94da-40f2-a17e-83a3fabe4913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5ea976d054e4e</value>
      <webElementGuid>d3feadc6-85f9-4ba4-abfc-f952801b32e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>7d0e8fcd-b007-48b2-b944-0666828c53fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5ea976d054e4e]</value>
      <webElementGuid>a6f61303-5449-47b8-9c09-dcd55cbb47d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59017117-bcd7-4c87-927f-2cace4140e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce95cf30-d7ba-41d7-b612-e05ff48704ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71f6a328-cf53-48ac-858d-8634e8d1bc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>b30a0074-20fc-4bf2-8f6d-bd3d08bd7f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5371b850-22b9-448f-ae6a-361e45f09359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles</value>
      <webElementGuid>0a95edfa-0df7-497c-888f-a1156a3fbcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5ea976d054e4e&quot;)</value>
      <webElementGuid>329a7708-3c75-483e-b8f9-7a6ce03ab6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5ea976d054e4e']</value>
      <webElementGuid>c2af1a50-3167-4f11-92fd-0ba3fa3212e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>94d4163b-d317-461f-ba07-7a1a68c030a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>a6bcd52e-e7ea-4ee3-8c5d-d7076617b616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>c621c10b-90ae-4930-bf0b-b0bc67b13d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>07be959c-93e1-45a5-af70-3116c891fc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5ea976d054e4e' and @name = 'acf[field_5ea976d054e4e]' and (text() = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles' or . = 'Please Select OneCulinaryTraveling &amp; LeisureGadgets &amp; TechnologyLifestyle &amp; ShoppingToys &amp; Collectibles')]</value>
      <webElementGuid>8d67723d-f097-49e4-a599-500969f9834c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
