<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneActionRacingSimulat_02dff3</name>
   <tag></tag>
   <elementGuidId>1bb501c8-170f-4228-8db8-751f7e498531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e758bca4e8cc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17439c2b-f2c6-495a-a4cc-8fad75c70f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e758bca4e8cc</value>
      <webElementGuid>d1c22786-7cf7-43a8-b50c-6f0c40d94382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>dc186d40-3ad2-47d0-b077-7be76868bde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e758bca4e8cc]</value>
      <webElementGuid>d9f42f7d-b398-4971-954b-275de0440433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6630a46f-4469-46bf-b51a-a5793d6455c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11dfc254-384b-4c26-b0bf-0f28b17f99ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1951d1c0-c5f0-41be-8802-e8273a2119ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>1744af1c-5d9f-48ec-abbf-c2b5dd93ca84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a94ae5f-71cb-4390-a5ec-3a5e7fdb6ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic</value>
      <webElementGuid>a923c75c-bb79-4365-b685-508862a459b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e758bca4e8cc&quot;)</value>
      <webElementGuid>850de8c9-87a2-470f-a94f-5c3cd58505af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      <webElementGuid>4a94e4d1-0dcd-47e2-98ce-1b5575ccb6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div/div[2]/select</value>
      <webElementGuid>8f3cb8cf-2566-4e31-a108-78bf52a65611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>30d93173-4ff2-43a4-87c2-a2aa892381f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>1344b970-684a-4613-b4e7-2eb4b8dc06a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4404fce1-5bca-4c65-b56b-568440392e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e758bca4e8cc' and @name = 'acf[field_5e758bca4e8cc]' and (text() = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic' or . = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic')]</value>
      <webElementGuid>7258880a-16c5-4ac1-b80d-a816c934d887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
