<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OnePlaystationXBoxNintendoPC</name>
   <tag></tag>
   <elementGuidId>5a88aff8-189c-4fcc-8860-51efd29cfd8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e75905014c81']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e75905014c81</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2199edb8-7b72-4d9f-a2bf-80441a9850dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e75905014c81</value>
      <webElementGuid>44a5ca08-2341-4b6b-9aad-432a87c3cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>205deceb-aa60-4c5c-bcb7-37b0153bc615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e75905014c81]</value>
      <webElementGuid>57f4d048-73e3-43df-877b-1dbff35d12fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>658cb776-f723-487f-a594-fd8cef698e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a6b49f9-9528-45c3-9dcc-2954fdccc0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fde89554-15af-4a12-b4c2-d105bc67cf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>bd2dd78d-0c01-4f8f-9b0c-e7c5a7f4ea49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af584e9f-e2e6-410e-8e75-1d281f4ade90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OnePlaystationXBoxNintendoPC</value>
      <webElementGuid>1d86e5b6-8c27-483b-a4ce-253557f94ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e75905014c81&quot;)</value>
      <webElementGuid>b27e6ca5-a789-473e-b77b-2b896b12a349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e75905014c81']</value>
      <webElementGuid>56b3f6c4-1ce8-436d-8242-11596743aaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[2]/div[2]/select</value>
      <webElementGuid>1f16d002-f74f-4333-8ccc-5553b91e7a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>5cbe2c67-9580-4099-aa5f-eaa53d2c1c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>9f1e28f9-9033-4582-93a1-374c00059616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>376b32d5-ebce-44a9-a8ad-06276f635bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e75905014c81' and @name = 'acf[field_5e75905014c81]' and (text() = 'Please Select OnePlaystationXBoxNintendoPC' or . = 'Please Select OnePlaystationXBoxNintendoPC')]</value>
      <webElementGuid>b133752c-7865-4e91-a953-47ba8044aab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
