<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_favoriteConsole</name>
   <tag></tag>
   <elementGuidId>9be03889-b6de-4eaf-ba69-d30588b37112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e75905014c81']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e75905014c81</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3038b4be-50aa-405d-8873-3614a8b66add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e75905014c81</value>
      <webElementGuid>a21b500c-a520-48b4-89b1-d6f619af154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>6484cbd7-6dfb-49e0-b149-e74806c7188d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e75905014c81]</value>
      <webElementGuid>d0c6cd3c-a263-4603-af78-2ef30a70f06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cae1555d-82b3-4c81-a4fd-3ac6a58675a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60154a5b-5adb-4a76-932c-5ba5dca27fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d714b989-6b80-4d70-8438-622b59ae2692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>54e29474-5d61-409b-97f7-1c0a25285137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>133df041-15e2-4a66-8a9d-f54473e3f6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OnePlaystationXBoxNintendoPC</value>
      <webElementGuid>d32c4397-3942-454b-bc90-1d2653fe7205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e75905014c81&quot;)</value>
      <webElementGuid>069b5bb9-f92b-44f0-8e23-39265968cca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e75905014c81']</value>
      <webElementGuid>403cd7a3-7bc0-407d-af8a-595f73ca82b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[2]/div[2]/select</value>
      <webElementGuid>ef10a6f0-e25d-48e6-ae1d-1b170d2483a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>661afcf2-fa03-4d83-9218-e01714d56d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>63accf08-8eba-4f44-99b4-6de8ed46706f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>6c9e6bd7-446e-4af8-84d1-bd7ed663ae38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e75905014c81' and @name = 'acf[field_5e75905014c81]' and (text() = 'Please Select OnePlaystationXBoxNintendoPC' or . = 'Please Select OnePlaystationXBoxNintendoPC')]</value>
      <webElementGuid>2e61fdd9-1cd5-426c-9db5-9dee85a0eab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
