<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Female_acffield_5ea3be750efb3</name>
   <tag></tag>
   <elementGuidId>36980f41-8ac1-475c-8a53-8e4a4926fe34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acf-field_5ea3be750efb3-female']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5ea3be750efb3-female</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcf48a40-554e-4d4b-9102-942284df3d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f08a7f41-43ae-43b3-88f6-cc64bb3c553a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5ea3be750efb3-female</value>
      <webElementGuid>2568ac90-3a4d-4c81-a5b5-7565bb974619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5ea3be750efb3]</value>
      <webElementGuid>5cebf768-2496-468d-bfbe-7cc95a427e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>dc5923a1-c693-4020-8aa9-7a993efbaba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5ea3be750efb3-female&quot;)</value>
      <webElementGuid>4233bd95-2521-4468-89e7-df8267b2a5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acf-field_5ea3be750efb3-female']</value>
      <webElementGuid>05e7a36e-7702-4a4e-93a8-32f85abe37ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[4]/div[2]/ul/li[2]/label/input</value>
      <webElementGuid>cb62bc83-40d8-4ed7-a951-6fff274fc89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/input</value>
      <webElementGuid>c42651ac-0df2-44c0-b1fc-d56763fdd1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'acf-field_5ea3be750efb3-female' and @name = 'acf[field_5ea3be750efb3]']</value>
      <webElementGuid>ea8572e6-b344-4fc4-87f8-c42bd67fd05a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
