<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Female_acffield_5ea3be750efb3</name>
   <tag></tag>
   <elementGuidId>4ee5f2e6-59a3-4f32-8e9c-a75011f6019d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acf-field_5ea3be750efb3-female']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5ea3be750efb3-female</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>477648b2-c93e-4d5b-8ddd-10b1e4afe2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>be6e05a1-98ae-4a20-a03a-ba6b75c65483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5ea3be750efb3-female</value>
      <webElementGuid>63ecb813-be51-41cd-b07d-d7dafa3a7876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5ea3be750efb3]</value>
      <webElementGuid>dcc011ee-043c-4b5d-b03d-ae2bf83cef8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>f6a4f27b-85ff-4c6e-ab8a-6387014f9574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5ea3be750efb3-female&quot;)</value>
      <webElementGuid>5fdadc6a-99a1-4bf3-b043-94c53817b8f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acf-field_5ea3be750efb3-female']</value>
      <webElementGuid>ffc77a89-11c6-41f8-84e6-096ccd14ce05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div[4]/div[2]/ul/li[2]/label/input</value>
      <webElementGuid>e7ec9a00-39c1-4766-8bf3-74e2c78cdee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/input</value>
      <webElementGuid>a6abf023-09d7-4d8f-899b-0917611e40cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'acf-field_5ea3be750efb3-female' and @name = 'acf[field_5ea3be750efb3]']</value>
      <webElementGuid>6efb4810-6d43-4da1-b895-3191ecd9e0d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
