<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select OneActionRacingSimulat_02dff3</name>
   <tag></tag>
   <elementGuidId>5e8b3e72-4deb-40ed-85d1-9db73efbb00f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acf-field_5e758bca4e8cc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>66a353dc-9eba-468c-a3d7-2adea5b2b85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf-field_5e758bca4e8cc</value>
      <webElementGuid>1fd96881-efd9-48d1-b707-5032aceea9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>95c3e8e1-baa6-4937-955c-33038ad4c072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acf[field_5e758bca4e8cc]</value>
      <webElementGuid>a08dc1a9-b2e8-4bae-897b-d945f28c4c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5be5491-2805-4e6c-9c17-bd7a51502c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>485ba274-0461-4d12-b68e-36851e394edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-multiple</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1abc7cb-edfc-4a9a-804a-d9c5c292ed10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>b751a1da-12c0-4f59-9ad4-5ff480d485b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow_null</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b43b61b-c4a5-4634-834e-a1f33bc5cc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic</value>
      <webElementGuid>a918471b-e703-441a-8b52-62807d6d363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf-field_5e758bca4e8cc&quot;)</value>
      <webElementGuid>1b3d7f3e-a57d-40ea-9430-43cfcbd5886b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='acf-field_5e758bca4e8cc']</value>
      <webElementGuid>fea15e84-e94c-4706-b6d9-7f1a383acbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/div/form/div[2]/div/div[2]/select</value>
      <webElementGuid>e8200eaa-7304-4bd0-8add-7a7cbd49f2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>fb76b8d0-d41b-4f45-90f9-a5339d959404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>513dd2f8-7540-465f-ada0-a6bb161f9881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>09cba367-8769-49db-b37d-90b9296cb623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'acf-field_5e758bca4e8cc' and @name = 'acf[field_5e758bca4e8cc]' and (text() = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic' or . = 'Please Select OneActionRacingSimulationStrategyShooterSportsFightingPuzzlePlatformRole PlayingBoard GameCard GameAdventureBeat Em UpTurn Based TacticsMusic')]</value>
      <webElementGuid>44c357bd-9360-4260-9afd-ca8804b3698c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
